//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesarrolloDocenteModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEC_ROLE
    {
        public SEC_ROLE()
        {
            this.SEC_USER_ROLE = new HashSet<SEC_USER_ROLE>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public bool REMOVED { get; set; }
        public string DESCRIPTION { get; set; }
    
        public virtual ICollection<SEC_USER_ROLE> SEC_USER_ROLE { get; set; }
    }
}
