//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesarrolloDocenteModel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SEC_SESSION
    {
        public long ID { get; set; }
        public int USERID { get; set; }
        public System.DateTime LOGIN_DATE { get; set; }
        public string IP_ADDRESS { get; set; }
        public string TOKEN { get; set; }
        public bool TOKEN_STATUS { get; set; }
        public Nullable<System.DateTime> LOGOUT_DATE { get; set; }
    
        public virtual SEC_USER SEC_USER { get; set; }
    }
}
